# Generated by Django 6.0.7 on 2026-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_company',
            field=models.BooleanField(default=False, verbose_name='Pode cadastrar mais empresas'),
        ),
    ]
