# Generated by Django 6.0.7 on 2026-07-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_can_add_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_companies',
            field=models.PositiveIntegerField(default=1, verbose_name='Máximo de empresas'),
        ),
    ]
