# Generated by Django 6.0.7 on 2026-07-20 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Razão social ou nome da empresa')),
                ('trade_name', models.CharField(blank=True, max_length=150, verbose_name='Nome fantasia')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='Identificador')),
                ('document', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF ou CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail da empresa')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('max_users', models.PositiveIntegerField(default=2, verbose_name='Limite de usuários')),
                ('is_active', models.BooleanField(default=True, verbose_name='Empresa ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
