# Generated by Django 6.0.7 on 2026-07-20 21:03

import apps.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='document',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[apps.companies.models.validate_cpf_cnpj], verbose_name='CPF ou CNPJ'),
        ),
    ]
